spring.application.name=gamehub-api

spring.datasource.url=jdbc:mysql://localhost:3306/gamehub
spring.datasource.username=${DB_USERNAME_GAMEHUB}
spring.datasource.password=${DB_PASSWORD_GAMEHUB}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=${JWT_SECRET_GAMEHUB}